title = "TableValue"  # From Git
gitRepoUrl = "https://github.com/data-oriented-house/TableValue" # From Git

gitSourceBranch = "main"
changelog = true

[home]
enabled = true
includeReadme = false

[[home.features]]
title = ""

[[home.features]]
title = "Reactive Tables"
description = "Ever wanted an InstanceValue but for tables? Well here you go."
image = "/TableValue.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "data-oriented-house"
projectName = "TableValue"
url = "https://data-oriented-house.github.io"
baseUrl = "/TableValue/"
tagline = "Lua's Reactive Table"

[navbar]
# hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2023 SolarScuffle-Bot (Sona). Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"